<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE catalogo [
    <!ELEMENT catalogo (libro+)>
<!ELEMENT libro (nombre, autor+, anyo_publicacion, genero+, precio, num_paginas+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT anyo_publicacion (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT num_paginas (#PCDATA)>
]>
    
<catalogo>
    <libro>
        <nombre>Fenix</nombre>
        <autor>Jorge Perez</autor>
        <anyo_publicacion>1982</anyo_publicacion>
        <genero>trama</genero>
        <precio>19.99</precio>
        <num_paginas>102</num_paginas>

    </libro>
    <libro>
        <nombre>Los Juegos del Hambre</nombre>
        <autor>Francisco Rodriguez</autor>
        <anyo_publicacion>1990</anyo_publicacion>
        <genero>Drama</genero>
        <precio>7.99</precio>
        <num_paginas>200</num_paginas>
    </libro> 
</catalogo>