<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE continente_aplicacion [
    <!ELEMENT continente_aplicacion (poblacion)+>
    <!ELEMENT poblacion (cantidad, etnia+, genero)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT etnia (#PCDATA)>
    <!ELEMENT genero (#PCDATA)>
]>
<continente_aplicacion>
    <poblacion>
        <cantidad>10000</cantidad>
        <etnia>Africana</etnia>
        <genero>H</genero>
    </poblacion>
    <poblacion>
        <cantidad>505000</cantidad>
        <etnia>Asiatica</etnia>
        <etnia>Europea</etnia>
        <genero>M</genero>
    </poblacion>
    <poblacion>
        <cantidad>505000</cantidad>
        <etnia>Cauc√°sica</etnia>
        <genero>M</genero>
    </poblacion>
</continente_aplicacion>