<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE dni [
    <!ELEMENT dni (persona+)>
    <!ELEMENT persona (id, nombre, apellidos, sexo, nacionalidad, nacimiento, emision, validez, num_soporte, domicilio, lugar_nacimiento, hijo_de)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT sexo (#PCDATA)>
    <!ELEMENT nacionalidad (#PCDATA)>
    <!ELEMENT nacimiento (#PCDATA)>
    <!ELEMENT emision (#PCDATA)>
    <!ELEMENT validez (#PCDATA)>
    <!ELEMENT num_soporte (#PCDATA)>
    <!ELEMENT domicilio (#PCDATA)>
    <!ELEMENT lugar_nacimiento (#PCDATA)>
    <!ELEMENT hijo_de (#PCDATA)>
]>
<dni>
    <persona>
        <id>12345678Z</id>
        <nombre>Triana</nombre>
        <apellidos>Rejano Ruge</apellidos>
        <sexo>H</sexo>
        <nacionalidad>Palma del Rio</nacionalidad>
        <nacimiento>25/01/2006</nacimiento>
        <emision>28/10/2021</emision>
        <validez>28/10/2026</validez>
        <num_soporte>CAS109954</num_soporte>
        <domicilio>Calle Genil 6 </domicilio>
        <lugar_nacimiento>Palma del Rio(Cordoba)</lugar_nacimiento>
        <hijo_de>José María y Manuela</hijo_de>
    </persona>

    <persona>
       <id>31894626C</id>
        <nombre>Manuel</nombre>
        <apellidos>Jimenez Segura</apellidos>
        <sexo>M</sexo>
        <nacionalidad>Fuente Carreteros</nacionalidad>
        <nacimiento>20/03/2000</nacimiento>
        <emision>27/10/2022</emision>
        <validez>27/10/2026</validez>
        <num_soporte>ESP109911</num_soporte>
        <domicilio>Calle Barcelona 6 </domicilio>
        <lugar_nacimiento>Fuente Carreteros(Cordoba)</lugar_nacimiento>
        <hijo_de>Maria y Roberto</hijo_de>
    </persona>
</dni>