<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE aplicacion_ficticia [
    <!ELEMENT aplicacion_ficticia (informacion+,usuario+,base_datos+, parametros+)>
    <!ELEMENT informacion (nombre+, version+, autor+)>
    <!ELEMENT base_datos (host+, puerto+, usuario_base+, contrasenya+, nombre_base_datos+)>
    <!ELEMENT usuario (tema+, idioma+, preferencias+)>
    <!ELEMENT parametros (tipo+, resolucion+)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT version (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT host (#PCDATA)>
    <!ELEMENT puerto (#PCDATA)>
    <!ELEMENT usuario_base (#PCDATA)>
    <!ELEMENT contrasenya (#PCDATA)>
    <!ELEMENT nombre_base_datos (#PCDATA)>
    <!ELEMENT tema (#PCDATA)>
    <!ELEMENT idioma (#PCDATA)>
    <!ELEMENT preferencias (#PCDATA)>
    <!ELEMENT tipo (#PCDATA)>
    <!ELEMENT resolucion (#PCDATA)>
]>
<aplicacion_ficticia>
    <informacion>
        <nombre>Jose</nombre>
        <version>1.01</version>
        <autor>Jose Ramon Rejano Ruge</autor>
    </informacion>
    <usuario>
        <tema>Oscuro</tema>
        <idioma>Espanyol</idioma>
        <preferencias>Bien configuradas</preferencias>
    </usuario>
    <base_datos>
        <host>28</host>
        <puerto>15.2.3.2</puerto>
        <usuario_base>Alberto22</usuario_base>
        <contrasenya>Albertito12345?</contrasenya>
        <nombre_base_datos>Alberto</nombre_base_datos>
    </base_datos>
    <parametros>
        <tipo>Movil y PC</tipo>
        <resolucion>1920X1080</resolucion>
    </parametros>
</aplicacion_ficticia>