=== JoseeR22/lenguaje2024_JoseRamonRejanoRuge/segundotrimestre/Tema10/contenido/xsd/xml1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  
  <xs:element name="catalogo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="libro" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="autor" type="xs:string"/>
              <xs:element name="anyo_publicacion" type="xs:gYear"/>
              <xs:element name="genero" type="xs:string"/>
              <xs:element name="precio" type="xs:decimal"/>
              <xs:element name="num_paginas" type="xs:int"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== JoseeR22/lenguaje2024_JoseRamonRejanoRuge/segundotrimestre/Tema10/contenido/xsd1.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalogo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../contenido/xsd/xml1.xsd">
    <libro>
        <nombre>Fenix</nombre>
        <autor>Jorge Perez</autor>
        <anyo_publicacion>1982</anyo_publicacion>
        <genero>trama</genero>
        <precio>19.99</precio>
        <num_paginas>102</num_paginas>

    </libro>
    <libro>
        <nombre>Los Juegos del Hambre</nombre>
        <autor>Francisco Rodriguez</autor>
        <anyo_publicacion>1990</anyo_publicacion>
        <genero>Drama</genero>
        <precio>7.99</precio>
        <num_paginas>200</num_paginas>
    </libro>
</catalogo>
