=== JoseeR22/lenguaje2024_JoseRamonRejanoRuge/segundotrimestre/Tema10/contenido/xsd/xml3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  
  <xs:element name="menu">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="bebidas">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="item" maxOccurs="unbounded" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="entrantes">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="item" maxOccurs="unbounded" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="platos">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="item" maxOccurs="unbounded" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="postres">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="item" maxOccurs="unbounded" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="salsas">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="item" maxOccurs="unbounded" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== JoseeR22/lenguaje2024_JoseRamonRejanoRuge/segundotrimestre/Tema10/contenido/xsd3.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../contenido/xsd/xml3.xsd">

    <bebidas>
        <item>Aquarius</item>
        <item>Agua</item>
        <item>Nestea</item>
        <item>Coca-Cola</item>
    </bebidas>
    <entrantes>
        <item>Patatas Bravas</item>
        <item>Aceitunas</item>
        <item>Croquetas de Rabo de Toro</item>
        <item>Gambas al Ajillo</item>
    </entrantes>
    <platos>
        <item>Carrilleras</item>
        <item>Tortilla de Patatas</item>
        <item>Solomillo de Cerdo</item>
        <item>Churrasco de Pollo</item>
        <item>San Jacobo</item>
        <item>Flamenquin Casero</item>
        <item>Pez Espada</item>
        <item>Lomo Alto Gallego</item>
        <item>Pulpo a la Gallega</item>
    </platos>
    <postres>
        <item>Tarta de Queso</item>
    </postres>
    <salsas>
        <item>Salsa Verde</item>
        <item>Salsa Pedro Ximenez</item>
        <item>Salsa Mojo Picon</item>
        <item>Salsa Roquefort</item>

    </salsas>
</menu>
