=== JoseeR22/lenguaje2024_JoseRamonRejanoRuge/segundotrimestre/Tema10/contenido/xsd/xml4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="dni">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="persona" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:string"/>
              <xs:element name="nombre" type="xs:string"/>
              <xs:element name="apellidos" type="xs:string"/>
              <xs:element name="sexo" type="xs:string"/>
              <xs:element name="nacionalidad" type="xs:string"/>
              <xs:element name="nacimiento" type="xs:string"/>
              <xs:element name="emision" type="xs:string"/>
              <xs:element name="validez" type="xs:string"/>
              <xs:element name="num_soporte" type="xs:string"/>
              <xs:element name="domicilio" type="xs:string"/>
              <xs:element name="lugar_nacimiento" type="xs:string"/>
              <xs:element name="hijo_de" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== JoseeR22/lenguaje2024_JoseRamonRejanoRuge/segundotrimestre/Tema10/contenido/xsd4.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<dni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../contenido/xsd/xml4.xsd">

    <persona>
        <id>12345678Z</id>
        <nombre>Triana</nombre>
        <apellidos>Rejano Ruge</apellidos>
        <sexo>H</sexo>
        <nacionalidad>Palma del Rio</nacionalidad>
        <nacimiento>25/01/2006</nacimiento>
        <emision>28/10/2021</emision>
        <validez>28/10/2026</validez>
        <num_soporte>CAS109954</num_soporte>
        <domicilio>Calle Genil 6 </domicilio>
        <lugar_nacimiento>Palma del Rio(Cordoba)</lugar_nacimiento>
        <hijo_de>José María y Manuela</hijo_de>
    </persona>

    <persona>
        <id>31894626C</id>
        <nombre>Manuel</nombre>
        <apellidos>Jimenez Segura</apellidos>
        <sexo>M</sexo>
        <nacionalidad>Fuente Carreteros</nacionalidad>
        <nacimiento>20/03/2000</nacimiento>
        <emision>27/10/2022</emision>
        <validez>27/10/2026</validez>
        <num_soporte>ESP109911</num_soporte>
        <domicilio>Calle Barcelona 6 </domicilio>
        <lugar_nacimiento>Fuente Carreteros(Cordoba)</lugar_nacimiento>
        <hijo_de>Maria y Roberto</hijo_de>
    </persona>
</dni>
