=== JoseeR22/lenguaje2024_JoseRamonRejanoRuge/segundotrimestre/Tema10/contenido/xsd/xml5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:element name="tarjeta_credito">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="tarjeta" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="numero" type="xs:string"/>
              <xs:element name="titular" type="xs:string"/>
              <xs:element name="fecha_vencimiento" type="xs:string"/>
              <xs:element name="tipo" type="xs:string"/>
              <xs:element name="entidad" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== JoseeR22/lenguaje2024_JoseRamonRejanoRuge/segundotrimestre/Tema10/contenido/xsd5.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tarjeta_credito xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../contenido/xsd/xml5.xsd">

    <tarjeta>
        <numero>ES123456789</numero>
        <titular>Juan Manuel Garcia Sanchez</titular>
        <fecha_vencimiento>25/02/2028</fecha_vencimiento>
        <tipo>fisica</tipo>
        <entidad>4444</entidad>
    </tarjeta>


    <tarjeta>
        <numero>ES567834785</numero>
        <titular>Javier Antonio Rodriguez Figueroa</titular>
        <fecha_vencimiento>25/02/2027</fecha_vencimiento>
        <tipo>virtual</tipo>
        <entidad>0000</entidad>
    </tarjeta>
</tarjeta_credito>
