=== JoseeR22/lenguaje2024_JoseRamonRejanoRuge/segundotrimestre/Tema10/contenido/xsd/xml6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  
  <xs:element name="ficha_tecnica">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="ficha" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="marca" type="xs:string"/>
              <xs:element name="modelo" type="xs:string"/>
              <xs:element name="anyo" type="xs:gYear"/>
              <xs:element name="matricula" type="xs:string"/>
              <xs:element name="combustible" type="xs:string"/>
              <xs:element name="potencia" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== JoseeR22/lenguaje2024_JoseRamonRejanoRuge/segundotrimestre/Tema10/contenido/xsd6.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ficha_tecnica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../contenido/xsd/xml6.xsd">


    <ficha>
        <marca>Seat</marca>
        <modelo>Leon 120d</modelo>
        <anyo>2002</anyo>
        <matricula>3000UYY</matricula>
        <combustible>Diesel</combustible>
        <potencia>92Kw</potencia>

    </ficha>
    <ficha>
        <marca>Ranger Rover</marca>
        <modelo>Evoque 2.5 TDI</modelo>
        <anyo>2013</anyo>
        <matricula>5200TTY</matricula>
        <combustible>Diesel</combustible>
        <potencia>120Kw</potencia>

    </ficha>
</ficha_tecnica>
